### ISSUE TITLE
Bug: Portfolio and contact page not loading correctly.

### ISSUE THREAD

**Issue by Frakko** [iamotso/personal-portfolio-fcc#1]
![image](https://user-images.githubusercontent.com/61921998/103034213-adcef600-4564-11eb-8956-3cd8c043fa0f.png)
![image](https://user-images.githubusercontent.com/61921998/103034235-b9222180-4564-11eb-88ff-dab5d06e7be9.png)

**Comment by techgirldiaries** [comment]
Hi Frakko, 

thanks for the message. Please, what browser are you using? I use Google Chrome browser, and it works perfectly. Also tried the page on Mozilla Firefox, it works perfectly. I changed the deployed site so try clicking on the menu to navigate the site.

New Link [here](https://otl-personal-portfolio.netlify.app)
 
Thank you and Happy Holidays!
Oluwakemi @iamotso xx

**Comment by Frakko** [comment]
Thank you for the feedback!

It's working correctly now. 😃 

Happy holidays!

**Comment by techgirldiaries** [comment]
Hi Frakko, you are welcome. Thanks and have a nice day.

Oluwakemi xx
